name: Crystals
version: "1.0"
api: ["1.0.0"]
main: Crystals.Crystals
author: "Minetox team"
description: "Crystals minigame"
depend: ["GTCore"]

commands:
    class:
        description: "Select game kit"
    blue:
        description: "join to blue team"
    red:
        description: "join to red team"
    yellow:
        description: "join to yellow team"
    green:
        description: "join to green team"
    stats:
        description: "show your game stats"
    msg:
        description: "send private message to another player"
    vote:
        description: "vote command"
    start:
        description: "start command"
    npc:
        description: "make a NPC entity"
    removeAll:
        description: "remove all entities"
    remove:
        description: "remove selected entity"
    cleantiles:
        desceiption: "remove all tiles"
    spawnboss:
        description: "spawns a iron golem boss"
    phase:
        description: "Shows game phase"
        aliases: ["faze"]